---
title: "Hot Spot analysis"
output:
  rmarkdown::html_vignette:
    toc: yes
    fig_width: 8
    fig_height: 6
vignette: >
  %\VignetteIndexEntry{Hot Spot analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      warning = FALSE, 
                      collapse = FALSE,
                      comment = "#>",
                      fig.align = "center")
```

```{r}
library(AmericasBarometer)
library(plyr)
library(ggplot2)
library(stringr)
library(RColorBrewer)

library(tidyverse)
library(ggthemes)
#library(ggrepel)
library(viridis)
library(extrafont)
library(corrplot)
library(corrgram)
#library(lsr)
#library(reshape2)
#library(OpenStreetMap)
library(sf)
library(sp)
library(rgdal)
library(scales)
library(knitr)
library(rmarkdown)
library(grid)
library(moments) 

mainDir <- getwd()
## If you save your analysis under vignette folder...
mainDirroot <- substring(mainDir, 0 , nchar(mainDir) - 10)


lapop.trends <- read.csv(paste0(mainDirroot, "/data-raw/MainDataFrame.csv"))

#table(lapop.trends$year, useNA= "ifany") 
## let's put 2019 & 2018 together

lapop.trends$year[lapop.trends$year=="2019"] <- "2018"
lapop.trends$year <- as.integer(lapop.trends$year)
lapop.trends$wave <- paste0(lapop.trends$ctrycollect, lapop.trends$year)


```






```{r}
## merge back provincia & prov 

lapop.trends$prov[is.na(lapop.trends$prov)] <- lapop.trends$provincia

prov <- read.csv(paste0(mainDirroot, "/data-raw/sig-prov2.csv"))
lapop.trends <- dplyr::left_join(x= lapop.trends, y = prov, by ="prov")

```

```{r message=FALSE, warning=FALSE}
### Build the indices
# 1. Authoritarianism index `aut_idx` 
aut_var <- c('dem2','dem11','jc13','jc10','jc15a')
lapop.trends$aut_idx <- make_idx(lapop.trends,aut_var,sgn=-1) 

# 2. Community Activity index `ca_idx`  
ca_var <- c('cp5','cp7','cp8','cp13','cp20','honcp22','honcp21a')
lapop.trends$ca_idx <- make_idx(lapop.trends,ca_var,sgn=-1)

# 3. Sympathy with government critics index `crit_idx`
crit_var <- c('d1','d2','d3','d4','e5','e15','e3','e16')
lapop.trends$crit_idx <- make_idx(lapop.trends,crit_var,sgn=-1)

# 4. Fear index `fear_idx` 
fear_var <- c('fear10','vic1ext','vic1exta','vic1hogar','aoj11',
                 'pese1','pese2','aoj17','diso7','diso8','diso10','diso18',
                 'diso14','diso16','diso17','vicbar1','vicbar1f','vicbar3',
                 'vicbar4','vicbar7','a4_crime','vic40','vic41','vic43',
                 'vic44','vic45','fear6f','fear6e','elsdiso18',
                 'elsdiso19')
lapop.trends$fear_idx <- make_idx(lapop.trends,fear_var,sgn=-1) 

# 5. Transparency index `transp_idx`  
transp_var <- c('honqt1','honqt2','honqt3','honqt4',
'honqt5','honqt6','honqt7','honqt8','honqt9','honqt10','honqt11','honqt12')
lapop.trends$transp_idx <- make_idx(lapop.trends,transp_var,sgn=-1)

# 6. Trust in Government Index `trust_idx` 
trust_var <- c('b1','b2','b3','b4','b6','b10a','b12','b13','b18','b21','b21a',
               'b32','b47a','n9','n11','n15','b3milx')
lapop.trends$trust_idx <- make_idx(lapop.trends,trust_var,sgn=-1)

# 7. Wealth index `wealth_idx` 
wealth_var <- c('r3','r4','r4a','r5','r6','r7','r8','r12','r14','r15','r18','r1','r16',
       'r26','q10new','q10g')
lapop.trends$wealth_idx <- make_idx(lapop.trends,wealth_var,sgn=-1)


```
```{r}
## Now aggregate index mean by admin 1 
# head(lapop.trends[ , c( "adm1name" ,"iso_3166_2","aut_idx" ,"ca_idx" ,"crit_idx" ,"fear_idx" ,"transp_idx" ,"trust_idx" ,"wealth_idx" )])
# Create subset of file with observation and selected variables & remove duplicated rows based on IDH
lapop.trends.map <- lapop.trends[ , c(  "iso_3166_2","aut_idx" ,"ca_idx" ,"crit_idx" ,"fear_idx" ,"transp_idx" ,"trust_idx" ,"wealth_idx" )]
  
 
  ## Aggregate numeric value  based on mean ####
lapop.trends.map2 <- lapop.trends.map %>%
    dplyr::group_by(iso_3166_2) %>%
    dplyr::summarise_all(dplyr::funs(mean(., na.rm = TRUE))) %>%
    dplyr::mutate_if(is.numeric, dplyr::funs(round(., 2)))
  
lapop.trends.map2 <- as.data.frame(lapop.trends.map2)
head(lapop.trends.map2)
```





```{r message=FALSE, warning=FALSE}



## getting correct district and gov from coordinates
geofile <- rgdal::readOGR(paste0(mainDirroot,"/data-raw/america_adm1_surv.geojson"))
geofile$id <- geofile$pcodehcr


 
#geofile.map.fort <- dplyr::left_join( x = MainDataFrameMap, y = geofile.fort, by = "id")

# View(geofile@data)
# levels(as.factor(geofile@data$code_op))
# levels(as.factor(geofile@data$adm1_code))
# substr(geofile@data$adm1_code, 1,3) %in% c("SLV", "HND", "GTM")

## get extend
geofile2 <- geofile[ substr(geofile@data$adm1_code, 1,3) %in% c("SLV", "HND", "GTM"), ]

## Fortify
geofile.fort <- fortify(geofile2, region = "iso_3166_2")
lapop.trends.map2$id <- lapop.trends.map2$iso_3166_2
geofile.map.fort <- dplyr::left_join( x = lapop.trends.map2, y = geofile.fort, by = "id")

## levels(as.factor(geofile2@data$adm1_code))
#bbox <- geofile2 %>%  sf::st_bbox()



# ## Map background
#  map <- get_map(c(left = as.numeric(bbox$xmin -  ((bbox$xmax - bbox$xmin)/10)), 
#                        bottom = as.numeric(bbox$ymin -  ((bbox$ymax - bbox$ymin)/10)), 
#                        right = as.numeric(bbox$xmax +  ((bbox$xmax - bbox$xmin)/10)), 
#                        top = as.numeric(bbox$ymax +   ((bbox$ymax - bbox$ymin)/10))), 
#                      maptype = "osm")


```



# 1. Authoritarianism index  


```{r}
plot1 <- ggplot( ) +
  geom_polygon(data = geofile.map.fort,
               aes(x = long, y = lat,  fill = aut_idx, 
                   group = group
                   ),
               colour = "white", alpha = 0.7 ) +
  coord_equal() +
  theme_map() +
  scale_fill_viridis(
                      name = "Average value",
                      guide = guide_legend( direction = "horizontal", label.position = "bottom",
                                            keyheight = unit(2, units = "mm"),  keywidth = unit(length(labels)*10, units = "mm"),
                                            title.position = 'top',  title.hjust = 0.5, label.hjust = 1, nrow = 1, byrow = T, reverse = T )) +
  labs(title = "Average Authoritarianism index value  " , 
       x = NULL, y = NULL,
       subtitle = "El Salvador, Hunduras & Guatemala",
       caption = "") +
   unhcRstyle::unhcr_theme() +
   theme(axis.ticks=element_blank(),
          axis.text.x =element_blank(),
          axis.text.y =element_blank(),
          axis.line = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank())
  
plot1
#ggpubr::ggarrange(unhcRstyle::left_align(plot1, c("caption", "subtitle", "title")), ncol = 1, nrow = 1)

```

# 2. Community Activity index 


```{r}
plot1 <- ggplot( ) +
  geom_polygon(data = geofile.map.fort,
               aes(x = long, y = lat,  fill = ca_idx, 
                   group = group
                   ),
               colour = "white", alpha = 0.7 ) +
  coord_equal() +
  theme_map() +
  scale_fill_viridis(
                      name = "Average value",
                      guide = guide_legend( direction = "horizontal", label.position = "bottom",
                                            keyheight = unit(2, units = "mm"),  keywidth = unit(length(labels)*10, units = "mm"),
                                            title.position = 'top',  title.hjust = 0.5, label.hjust = 1, nrow = 1, byrow = T, reverse = T )) +
  labs(title = "Average Community Activity index value  " , 
       x = NULL, y = NULL,
       subtitle = "El Salvador, Hunduras & Guatemala",
       caption = "") +
   unhcRstyle::unhcr_theme() +
   theme(axis.ticks=element_blank(),
          axis.text.x =element_blank(),
          axis.text.y =element_blank(),
          axis.line = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank())
  
plot1
#ggpubr::ggarrange(unhcRstyle::left_align(plot1, c("caption", "subtitle", "title")), ncol = 1, nrow = 1)

```


# 3. Sympathy with government critics index 

```{r}
plot1 <- ggplot( ) +
  geom_polygon(data = geofile.map.fort,
               aes(x = long, y = lat,  fill = crit_idx, 
                   group = group
                   ),
               colour = "white", alpha = 0.7 ) +
  coord_equal() +
  theme_map() +
  scale_fill_viridis(
                      name = "Average value",
                      guide = guide_legend( direction = "horizontal", label.position = "bottom",
                                            keyheight = unit(2, units = "mm"),  keywidth = unit(length(labels)*10, units = "mm"),
                                            title.position = 'top',  title.hjust = 0.5, label.hjust = 1, nrow = 1, byrow = T, reverse = T )) +
  labs(title = "Average Sympathy with government critics value  " , 
       x = NULL, y = NULL,
       subtitle = "El Salvador, Hunduras & Guatemala",
       caption = "") +
   unhcRstyle::unhcr_theme() +
   theme(axis.ticks=element_blank(),
          axis.text.x =element_blank(),
          axis.text.y =element_blank(),
          axis.line = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank())
  
plot1
#ggpubr::ggarrange(unhcRstyle::left_align(plot1, c("caption", "subtitle", "title")), ncol = 1, nrow = 1)

```

# 4. Fear index 


```{r}
plot1 <- ggplot( ) +
  geom_polygon(data = geofile.map.fort,
               aes(x = long, y = lat,  fill = fear_idx, 
                   group = group
                   ),
               colour = "white", alpha = 0.7 ) +
  coord_equal() +
  theme_map() +
  scale_fill_viridis(
                      name = "Average value",
                      guide = guide_legend( direction = "horizontal", label.position = "bottom",
                                            keyheight = unit(2, units = "mm"),  keywidth = unit(length(labels)*10, units = "mm"),
                                            title.position = 'top',  title.hjust = 0.5, label.hjust = 1, nrow = 1, byrow = T, reverse = T )) +
  labs(title = "Average Fear index value  " , 
       x = NULL, y = NULL,
       subtitle = "El Salvador, Hunduras & Guatemala",
       caption = "") +
   unhcRstyle::unhcr_theme() +
   theme(axis.ticks=element_blank(),
          axis.text.x =element_blank(),
          axis.text.y =element_blank(),
          axis.line = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank())
  
plot1
#ggpubr::ggarrange(unhcRstyle::left_align(plot1, c("caption", "subtitle", "title")), ncol = 1, nrow = 1)

```

# 5. Transparency index 



```{r}
plot1 <- ggplot( ) +
  geom_polygon(data = geofile.map.fort,
               aes(x = long, y = lat,  fill = transp_idx, 
                   group = group
                   ),
               colour = "white", alpha = 0.7 ) +
  coord_equal() +
  theme_map() +
  scale_fill_viridis(
                      name = "Average value",
                      guide = guide_legend( direction = "horizontal", label.position = "bottom",
                                            keyheight = unit(2, units = "mm"),  keywidth = unit(length(labels)*10, units = "mm"),
                                            title.position = 'top',  title.hjust = 0.5, label.hjust = 1, nrow = 1, byrow = T, reverse = T )) +
  labs(title = "Average Transparency index value  " , 
       x = NULL, y = NULL,
       subtitle = "El Salvador, Hunduras & Guatemala",
       caption = "") +
   unhcRstyle::unhcr_theme() +
   theme(axis.ticks=element_blank(),
          axis.text.x =element_blank(),
          axis.text.y =element_blank(),
          axis.line = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank())
  
plot1
#ggpubr::ggarrange(unhcRstyle::left_align(plot1, c("caption", "subtitle", "title")), ncol = 1, nrow = 1)

```

# 6. Trust in Government Index 

```{r}
plot1 <- ggplot( ) +
  geom_polygon(data = geofile.map.fort,
               aes(x = long, y = lat,  fill = trust_idx, 
                   group = group
                   ),
               colour = "white", alpha = 0.7 ) +
  coord_equal() +
  theme_map() +
  scale_fill_viridis(
                      name = "Average value",
                      guide = guide_legend( direction = "horizontal", label.position = "bottom",
                                            keyheight = unit(2, units = "mm"),  keywidth = unit(length(labels)*10, units = "mm"),
                                            title.position = 'top',  title.hjust = 0.5, label.hjust = 1, nrow = 1, byrow = T, reverse = T )) +
  labs(title = "Average Trust index value  " , 
       x = NULL, y = NULL,
       subtitle = "El Salvador, Hunduras & Guatemala",
       caption = "") +
   unhcRstyle::unhcr_theme() +
   theme(axis.ticks=element_blank(),
          axis.text.x =element_blank(),
          axis.text.y =element_blank(),
          axis.line = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank())
  
plot1
#ggpubr::ggarrange(unhcRstyle::left_align(plot1, c("caption", "subtitle", "title")), ncol = 1, nrow = 1)

```

 

# 7. Wealth index  

```{r}
plot1 <- ggplot( ) +
  geom_polygon(data = geofile.map.fort,
               aes(x = long, y = lat,  fill = wealth_idx, 
                   group = group
                   ),
               colour = "white", alpha = 0.7 ) +
  coord_equal() +
  theme_map() +
  scale_fill_viridis(
                      name = "Average value",
                      guide = guide_legend( direction = "horizontal", label.position = "bottom",
                                            keyheight = unit(2, units = "mm"),  keywidth = unit(length(labels)*10, units = "mm"),
                                            title.position = 'top',  title.hjust = 0.5, label.hjust = 1, nrow = 1, byrow = T, reverse = T )) +
  labs(title = "Average Wealth index value  " , 
       x = NULL, y = NULL,
       subtitle = "El Salvador, Hunduras & Guatemala",
       caption = "") +
   unhcRstyle::unhcr_theme() +
   theme(axis.ticks=element_blank(),
          axis.text.x =element_blank(),
          axis.text.y =element_blank(),
          axis.line = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank())
  
plot1
#ggpubr::ggarrange(unhcRstyle::left_align(plot1, c("caption", "subtitle", "title")), ncol = 1, nrow = 1)

```

```{r}
# library(tidyverse)
# library(sf)
# 
# if (!fs::dir_exists("mapdata")) {
#   fs::dir_create("mapdata")
#   
#   adms <- 
#     list(honduras = "https://data.humdata.org/dataset/bd62fb53-64d3-478f-9ca8-38e4a2de19c0/resource/34688cf1-3cad-4d51-a6b5-7726de70f4e7/download/hnd_adm_sinit_20161005_shp.zip",
#          salvador = "https://data.humdata.org/dataset/08bfc7f6-3acc-45df-a69a-b853cf1cff05/resource/b693e3e1-f7c4-4ebe-afb7-453d62abd417/download/slv_adm_gadm_2021_shp.zip",
#          guatemala = "https://data.humdata.org/dataset/0b20f310-7d22-479c-b7e2-e1bb9737fa72/resource/86f38f11-8062-4a09-b088-fbb581a051fd/download/gtm_adm_ocha_conred_2019_shp.zip")
#   
#   adms %>% walk(~httr::GET(., httr::write_disk(fs::path_temp(fs::path_file(.)), overwrite = TRUE)))
#   
#   adms %>% walk(~unzip(fs::path_temp(fs::path_file(.)), exdir = "mapdata", junkpaths = TRUE))
# }
# 
# honduras <- st_read("mapdata/hnd_admbnda_adm1_sinit_20161005.shp")
# elsalvador <- st_read("mapdata/slv_admbnda_adm1_gadm_20210204.shp")
# guatemala <- st_read("mapdata/gtm_admbnda_adm1_ocha_conred_20190207.shp")
# 
# acled <- 
#   list("Salvador", "Guatemala", "Honduras") %>% 
#   map_dfr(~jsonlite::fromJSON(glue::glue("https://api.acleddata.com/acled/read?key={Sys.getenv('ACLED_API_KEY')}&email={Sys.getenv('UNHCR_ACCOUNT_EMAIL')}&country={.}&limit=0"))$data) %>% 
#   mutate(across(c(year, latitude, longitude), as.numeric),
#          geometry = map2(latitude, longitude, ~st_point(c(.y, .x))) %>% st_as_sfc(crs = 4326)) %>% 
#   as_tibble()
# 
# acled_map <- function(place, placemap) {
#   acled %>% 
#     filter(event_type == "Violence against civilians", year != 2021, country == place) %>% 
#     ggplot() +
#     geom_hex(aes(longitude, latitude)) +
#     scale_fill_steps(low = "white", high = "#EF4A60", name = "# of incidents") +
#     geom_sf(data = placemap, fill = NA) +
#     labs(x = NULL, y = NULL,
#          title = place, subtitle = "Violence against civilians (2018-2020)",
#          caption = "Data source: The Armed Conflict Location & Event Data Project") +
#     guides(fill = guide_colorsteps(title.position = "top", barwidth = unit(2.5, "inches"))) +
#     theme_minimal() +
#     theme(legend.position = "bottom")
# }
# 
# hnd <- acled_map("Honduras", honduras)
# slv <- acled_map("El Salvador", salvador)
# gtm <- acled_map("Guatemala", guatemala)
# 
# ggsave("hnd.png", hnd)
# ggsave("slv.png", slv)
# ggsave("gtm.png", gtm)
```

