<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Building Indices • AmericasBarometer</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/yeti/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Building Indices">
<meta property="og:description" content="AmericasBarometer">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">AmericasBarometer</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.1.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/Survey_wave_content.html">Survey wave content</a>
    </li>
    <li>
      <a href="../articles/Trends_per_year_by_topic.html">Trends per year by topic</a>
    </li>
    <li>
      <a href="../articles/Explaining_Intention_Migrate.html">Explaining_Intention_Migrate</a>
    </li>
    <li>
      <a href="../articles/Explaining_fear_being_victim.html">Explaining_fear_being_victim</a>
    </li>
    <li>
      <a href="../articles/Explaining_risk_bribes.html">Explaining_risk_bribes</a>
    </li>
    <li>
      <a href="../articles/Building_indices.html">Building indices</a>
    </li>
    <li>
      <a href="../articles/Profiling_Intended_Migrant.html">Profiling Intended Migrant</a>
    </li>
  </ul>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/unhcr-americas/LAPOP-SMA/">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="Building_indices_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Building Indices</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/unhcr-americas/LAPOP-SMA/blob/master/vignettes/Building_indices.Rmd"><code>vignettes/Building_indices.Rmd</code></a></small>
      <div class="hidden name"><code>Building_indices.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<p>An initial step in the analysis consist in the creation a series of indices to better understand different group of variables together.</p>
<p>Those indices can be built with principal component analyis and require the imputation of missing values.</p>
<p>We’ll load all three 2014 datasets and construct a data frame containing the columns we want.</p>
</div>
<div id="authoritarianism-index" class="section level2">
<h2 class="hasAnchor">
<a href="#authoritarianism-index" class="anchor"></a>Authoritarianism index</h2>
<p>This index will measure the a respondent’s inclination toward authoritarian political attitudes. The following variables were measured in all three countries and correlate strongly with each other:</p>
<ul>
<li>
<code>dem2</code>: Support for democracy or dictatorship (1=either is OK, 2=democracy, 3=dictatorship)</li>
<li>
<code>dem11</code>: Support for mano dura policies (1=iron fist, 2=broad participation)</li>
<li>
<code>jc10</code>: Coup is justified when crime is high (1=yes, 2=no)</li>
<li>
<code>jc13</code>: Coup is justified when corruption is high (1=yes, 2=no)</li>
<li>
<code>jc15a</code>: President justified in governing without legislature during crisis (1=yes, 2=no)</li>
</ul>
<pre><code>#&gt; All variables for the index are present in the datasetInputed missing percent values: c(0.0218388294387421, 0.05503385018563, 0.0596200043677659, 0.052413190652981, 0.0681371478488753)
#&gt;  Inputed missing percent values: c("dem11", "dem2", "jc10", "jc13", "jc15a")
#&gt; The first componnent retained 40.128% of the variance.</code></pre>
<div id="principal-componnent-analysis-without-imputation" class="section level3">
<h3 class="hasAnchor">
<a href="#principal-componnent-analysis-without-imputation" class="anchor"></a>Principal Componnent Analysis without imputation</h3>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-4-1.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>#&gt; Importance of components:
#&gt;                           PC1    PC2    PC3     PC4     PC5
#&gt; Standard deviation     0.7370 0.6143 0.4676 0.31602 0.29372
#&gt; Proportion of Variance 0.4098 0.2848 0.1650 0.07536 0.06509
#&gt; Cumulative Proportion  0.4098 0.6946 0.8596 0.93491 1.00000</code></pre>
<p>41% of variance is concentrated in the first component.</p>
</div>
<div id="missing-values-imputation" class="section level3">
<h3 class="hasAnchor">
<a href="#missing-values-imputation" class="anchor"></a>Missing values imputation</h3>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-6-1.png" width="700" style="display: block; margin: auto;"></p>
<p>Most variables had fairly similar numbers of missing values; people were least willing to talk about expanded presidential powers (<code>jc15a</code>) and most willing to talk about mano dura policies (<code>dem11</code>).</p>
<p>What does PCA look like for one of the five imputed datasets?</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-7-1.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>#&gt; Importance of components:
#&gt;                           PC1    PC2    PC3     PC4     PC5
#&gt; Standard deviation     0.7329 0.6160 0.4711 0.33338 0.29818
#&gt; Proportion of Variance 0.4013 0.2835 0.1658 0.08303 0.06642
#&gt; Cumulative Proportion  0.4013 0.6848 0.8506 0.93358 1.00000</code></pre>
<p>PCA results look very similar to what we saw without imputation, which is good.</p>
</div>
<div id="scatterplot-matrix" class="section level3">
<h3 class="hasAnchor">
<a href="#scatterplot-matrix" class="anchor"></a>Scatterplot matrix</h3>
<p>The distribution of PC1 seems to fall into three bands, suggesting that the index is dominated by one variable that takes on three values.</p>
<p>All of our imputations are really well-correlated, and the lowest-valued band is the most heavily-populated one.</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-9-1.png" width="960" style="display: block; margin: auto;"></p>
</div>
<div id="influence-of-indicator" class="section level3">
<h3 class="hasAnchor">
<a href="#influence-of-indicator" class="anchor"></a>Influence of indicator</h3>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-10-1.png" width="960" style="display: block; margin: auto;"></p>
<p>Compared to the lowest quantile, the highest quantile of our proposed index has much higher values for <code>dem2</code> and decreasing values for everything else. Lower values for <code>dem2</code> indicate a preference for democracy, while higher values of the binary variables indicate less-authoritarian attitudes. The scale is therefore in pointing in the right direction.</p>
<p><code>dem2</code> is the only variable that takes on three values; its strong slope in this plot suggests that it is the dominant factor in our index.</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-12-1.png" width="700" style="display: block; margin: auto;"></p>
<p>While all five variables have an impact on the composite index, <code>dem2</code> has by far the strongest influence.</p>
<p>We can be more rigorous about this by calculating p-values. We’ll have to do this differently for <code>dem2</code> (which takes on three values) than for the ones that only take on two. All are significantly-correlated (especially <code>dem2</code>).</p>
<pre><code>#&gt;       var        est
#&gt; 1 dem2_lo  2.1988749
#&gt; 2 dem2_hi  2.5657717
#&gt; 3   dem11 -0.5739431
#&gt; 4    jc13 -0.6700082
#&gt; 5    jc10 -0.6890520
#&gt; 6   jc15a -0.4643632
#&gt;                                                                                                                pval
#&gt; 1 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
#&gt; 2 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
#&gt; 3 0.000000000000000000000000000000000000000000000000000000000000000000000000047468539512792707789411616888831318984
#&gt; 4 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001414378
#&gt; 5 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004165395216552312
#&gt; 6 0.000000000000000000472477405886798687632994864469929801078793335882124787214464411988501524319872260093688964844</code></pre>
</div>
</div>
<div id="sympathy-with-government-critics-index" class="section level2">
<h2 class="hasAnchor">
<a href="#sympathy-with-government-critics-index" class="anchor"></a>Sympathy with government critics index</h2>
<p>This index measures a respondent’s level of sympathy with government critics (aka a measure of political tolerance). It includes the following variables:</p>
<ul>
<li>
<code>d1</code>: Approval of government critics’ right to vote (1=low, 10=high)</li>
<li>
<code>d2</code>: Approval of government critics’ right to hold peaceful demonstrations</li>
<li>
<code>d3</code>: Approval of government critics’ right to run for office</li>
<li>
<code>d4</code>: Approval of government critics’ right to make speeches</li>
<li>
<code>e5</code>: Approval of participation in legal demonstrations (1=disapprove, 10=approve)</li>
<li>
<code>e15</code>: Approval of blocking roads during protest (1=approve, 10=disapprove)</li>
<li>
<code>e3</code>: Approval of groups attempting to overthrow government (1=disapprove, 10=approve)</li>
<li>
<code>e16</code>: Approval of vigilante justice (1=disapprove, 10=approve)</li>
</ul>
<div id="principal-componnent-analysis-without-imputation-1" class="section level3">
<h3 class="hasAnchor">
<a href="#principal-componnent-analysis-without-imputation-1" class="anchor"></a>Principal Componnent Analysis without imputation</h3>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-16-1.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>#&gt; Importance of components:
#&gt;                           PC1    PC2    PC3    PC4     PC5     PC6    PC7
#&gt; Standard deviation     4.9201 3.2383 2.8796 2.5338 2.18764 2.08894 1.7304
#&gt; Proportion of Variance 0.3792 0.1643 0.1299 0.1006 0.07496 0.06835 0.0469
#&gt; Cumulative Proportion  0.3792 0.5434 0.6733 0.7739 0.84882 0.91716 0.9641
#&gt;                            PC8
#&gt; Standard deviation     1.51473
#&gt; Proportion of Variance 0.03594
#&gt; Cumulative Proportion  1.00000</code></pre>
<p>38% of variance is in the first principal component – pretty typical for our composite indices.</p>
</div>
<div id="missing-values-imputation-1" class="section level3">
<h3 class="hasAnchor">
<a href="#missing-values-imputation-1" class="anchor"></a>Missing values imputation</h3>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-17-1.png" width="700" style="display: block; margin: auto;"></p>
<p>None of these involved a lot of imputation; in general the questions about the political rights of government critics (<code>d1</code>,<code>d2</code>,<code>d3</code>,<code>d4</code>) needed more imputation than the questions about the appropriateness of protests or anti-government activity.</p>
<p>Look at PCA for one of our imputed datasets:</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-18-1.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>#&gt; Importance of components:
#&gt;                          PC1    PC2    PC3    PC4     PC5     PC6     PC7
#&gt; Standard deviation     4.900 3.2469 2.9053 2.5461 2.19176 2.08978 1.73913
#&gt; Proportion of Variance 0.375 0.1647 0.1318 0.1013 0.07503 0.06821 0.04724
#&gt; Cumulative Proportion  0.375 0.5396 0.6715 0.7727 0.84777 0.91598 0.96322
#&gt;                            PC8
#&gt; Standard deviation     1.53465
#&gt; Proportion of Variance 0.03678
#&gt; Cumulative Proportion  1.00000</code></pre>
<p>PCA results look very similar to what we saw without imputation, which is good.</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-19-1.png" width="960" style="display: block; margin: auto;"></p>
</div>
<div id="scatterplot-matrix-1" class="section level3">
<h3 class="hasAnchor">
<a href="#scatterplot-matrix-1" class="anchor"></a>Scatterplot matrix</h3>
<p>This scatterplot shows a very continuous distribution along PC1; a good sign that a single variable doesn’t really dominate this index. It helps that each variable can take a large number of values, meaning that a large number of combinations are possible (and present).</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-20-1.png" width="960" style="display: block; margin: auto;"></p>
<p>All of our imputations are really well-correlated, and the distributions of PC1 look well-behaved.</p>
</div>
<div id="influence-of-indicator-1" class="section level3">
<h3 class="hasAnchor">
<a href="#influence-of-indicator-1" class="anchor"></a>Influence of indicator</h3>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-21-1.png" width="960" style="display: block; margin: auto;"></p>
<p>All variables increase with PC1 – high values indicate greater approval of dissident rights, so our index is pointing in the right direction. The steepest slope (i.e. the largest difference between the lowest and highest quartiles) belongs to <code>d2</code> (approval of critics’ right to hold peaceful demonstrations), while <code>e3</code> (approval of groups trying to overthrow the government) has the shallowest slope. Even the most tolerant people don’t have much patience with revolutionaries.</p>
<p>Let’s normalize and average PC1:</p>
<p>Now, let’s see how each variable contributes to the composite score:</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-23-1.png" width="700" style="display: block; margin: auto;"></p>
<p>This is roughly what we’d expect – all variables have an influence, with <code>d2</code> the strongest and <code>e3</code> the weakest.</p>
<p>We can be more rigorous about this by calculating p-values. As all variables are measured on a 1-10 scale, we can do this using linear regression.</p>
<pre><code>#&gt;                                                                                                                                                                                                                                                                                  d1 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                                                                                                                                                                  d2 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                                                                                                                                                                  d3 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                                                                                                                                                                  d4 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                                                                                                                                                                  e3 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000198591645738544570327758111285196510991764737136261881937633459825766029510673611046640621351913402377091165284758016211595010526156901953483711439408722345 
#&gt;                                                                                                                                                                                                                                                                                  e5 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                                                                                                                                                                 e15 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002408719 
#&gt;                                                                                                                                                                                                                                                                                 e16 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016479458362802270183120361553438328009697788273415356430352092868629836119</code></pre>
<p>All are extremely significant.</p>
<p>We’ll visualize <code>e16</code> (approval of vigilante justice); modify the code below if you want to look at the others:</p>
<pre><code>#&gt; 
#&gt; Call:
#&gt; lm(formula = q ~ w, data = e16)
#&gt; 
#&gt; Residuals:
#&gt;     Min      1Q  Median      3Q     Max 
#&gt; -6.9272 -2.2198 -0.5706  1.9702  7.6321 
#&gt; 
#&gt; Coefficients:
#&gt;             Estimate Std. Error t value            Pr(&gt;|t|)    
#&gt; (Intercept)  4.25657    0.04486   94.88 &lt;0.0000000000000002 ***
#&gt; w           -1.42591    0.04485  -31.80 &lt;0.0000000000000002 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; Residual standard error: 3.026 on 4547 degrees of freedom
#&gt; Multiple R-squared:  0.1819, Adjusted R-squared:  0.1817 
#&gt; F-statistic:  1011 on 1 and 4547 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-25-1.png" width="700" style="display: block; margin: auto;"></p>
<p>The correlation is far from perfect, but people with a high value of our index are significantly more likely to appove of vigilante justice. It’s interesting that <code>e16</code> seems fairly polarized, with a lot of people answering either 1 or 10.</p>
<p>Finally, check these values against the comments in <code>make_indices.R</code> to be sure we’re calculating the same index:</p>
<pre><code>#&gt;          0%         25%         50%         75%        100% 
#&gt; -3.15962365 -0.59446098  0.08714615  0.68098277  1.85718532</code></pre>
</div>
</div>
<div id="community-activity-index" class="section level2">
<h2 class="hasAnchor">
<a href="#community-activity-index" class="anchor"></a>Community Activity index</h2>
<ul>
<li>
<code>cp5</code>: Tried to solve a community problem (1=Once a week, 2=Once or twice a month, 3=Once or twice a year, 4=Never)</li>
<li>
<code>cp7</code>: Attended meetings of Parent Association (1=Once a week, 2=Once or twice a month, 3=Once or twice a year, 4=Never)</li>
<li>
<code>cp8</code>: Attended meetings of Community Improvement Association (1=Once a week, 2=Once or twice a month, 3=Once or twice a year, 4=Never)</li>
<li>
<code>cp13</code>: Attended meetings of a Political Party (1=Once a week, 2=Once or twice a month, 3=Once or twice a year, 4=Never)</li>
<li>
<code>cp20</code>: Attended meetings of Women’s Group (1=Once a week, 2=Once or twice a month, 3=Once or twice a year, 4=Never)</li>
</ul>
<div id="principal-componnent-analysis-without-imputation-2" class="section level3">
<h3 class="hasAnchor">
<a href="#principal-componnent-analysis-without-imputation-2" class="anchor"></a>Principal Componnent Analysis without imputation</h3>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-28-1.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>#&gt; Importance of components:
#&gt;                           PC1    PC2    PC3    PC4     PC5
#&gt; Standard deviation     1.0948 0.8720 0.7153 0.6014 0.53463
#&gt; Proportion of Variance 0.3844 0.2439 0.1641 0.1160 0.09167
#&gt; Cumulative Proportion  0.3844 0.6282 0.7923 0.9083 1.00000</code></pre>
<p>Without any imputation, 38.4% of variance is concentrated on the first principal component.</p>
</div>
<div id="missing-values-imputation-2" class="section level3">
<h3 class="hasAnchor">
<a href="#missing-values-imputation-2" class="anchor"></a>Missing values imputation</h3>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-29-1.png" width="700" style="display: block; margin: auto;"></p>
<p>None of the variables stand out as needing too much imputation, with the CLEAR exception of <code>cp20</code>, which was question conditioned on the subject being female.</p>
<p>Presumably, what the imputation is telling us is that the individual in question would go to women’s groups if men were invited.</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-30-1.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>#&gt; Importance of components:
#&gt;                           PC1    PC2    PC3    PC4    PC5
#&gt; Standard deviation     1.0882 0.9017 0.7345 0.6383 0.5821
#&gt; Proportion of Variance 0.3607 0.2477 0.1643 0.1241 0.1032
#&gt; Cumulative Proportion  0.3607 0.6084 0.7727 0.8968 1.0000</code></pre>
<p>With the imputation, we don’t have much change; 37% of variance is concentrated on the first principal component.</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-31-1.png" width="700" style="display: block; margin: auto;"></p>
</div>
<div id="scatterplot-matrix-2" class="section level3">
<h3 class="hasAnchor">
<a href="#scatterplot-matrix-2" class="anchor"></a>Scatterplot matrix</h3>
<p>Variation along PC1 seems to be fairly continuous, indicating that this index isn’t dominated by a single variable.</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-32-1.png" width="700" style="display: block; margin: auto;"></p>
<p>Our different imputed datasets correlate strongly, and the distribution skews toward low values of PC1.</p>
</div>
<div id="influence-of-indicator-2" class="section level3">
<h3 class="hasAnchor">
<a href="#influence-of-indicator-2" class="anchor"></a>Influence of indicator</h3>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-33-1.png" width="960" style="display: block; margin: auto;"></p>
<p>All five variables decrease as the index increases; recall that larger values correspond to less-frequent participation, so our index is pointing in the right direction. Because <code>cp7</code> (parent’s association attendance) has the steepest slope, we suspect that it will have the strongest influence on the composite index.</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-34-1.png" width="700" style="display: block; margin: auto;"></p>
<p>All variables influence the index; the weakest influence comes from <code>cp13</code> (Attended meetings of a political party), apparently because even the most-engaged quartile hardly did this at all.</p>
<p>Since all variables take on multiple values, we will check p-values using linear regression.</p>
<pre><code>#&gt;                                                                                                                                     cp5 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                     cp7 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                     cp8 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                    cp13 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000808175230106566608967928220854681809363772322659795131435595298529 
#&gt;                                                                                                                                    cp20 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006726048</code></pre>
<p>All p-values are highly-significant.</p>
<pre><code>#&gt; 
#&gt; Call:
#&gt; lm(formula = q ~ w, data = cp7)
#&gt; 
#&gt; Residuals:
#&gt;     Min      1Q  Median      3Q     Max 
#&gt; -1.8332 -0.5264  0.1817  0.4620  2.8005 
#&gt; 
#&gt; Coefficients:
#&gt;             Estimate Std. Error t value            Pr(&gt;|t|)    
#&gt; (Intercept)  3.14329    0.01135  276.96 &lt;0.0000000000000002 ***
#&gt; w            0.61505    0.01136   54.16 &lt;0.0000000000000002 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; Residual standard error: 0.7678 on 4575 degrees of freedom
#&gt; Multiple R-squared:  0.3907, Adjusted R-squared:  0.3906 
#&gt; F-statistic:  2934 on 1 and 4575 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-36-1.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>#&gt; 
#&gt; Call:
#&gt; lm(formula = q ~ w, data = cp13)
#&gt; 
#&gt; Residuals:
#&gt;      Min       1Q   Median       3Q      Max 
#&gt; -3.00300  0.08428  0.16593  0.28678  0.90726 
#&gt; 
#&gt; Coefficients:
#&gt;             Estimate Std. Error t value            Pr(&gt;|t|)    
#&gt; (Intercept) 3.747868   0.008641   433.7 &lt;0.0000000000000002 ***
#&gt; w           0.152943   0.008643    17.7 &lt;0.0000000000000002 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; Residual standard error: 0.5842 on 4568 degrees of freedom
#&gt; Multiple R-squared:  0.06414,    Adjusted R-squared:  0.06394 
#&gt; F-statistic: 313.1 on 1 and 4568 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-37-1.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>#&gt; 
#&gt; Call:
#&gt; lm(formula = q ~ w, data = cp20)
#&gt; 
#&gt; Residuals:
#&gt;      Min       1Q   Median       3Q      Max 
#&gt; -2.81929 -0.08536  0.08780  0.26096  1.23991 
#&gt; 
#&gt; Coefficients:
#&gt;             Estimate Std. Error t value            Pr(&gt;|t|)    
#&gt; (Intercept)  3.72940    0.01237   301.6 &lt;0.0000000000000002 ***
#&gt; w            0.32434    0.01272    25.5 &lt;0.0000000000000002 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; Residual standard error: 0.6009 on 2365 degrees of freedom
#&gt; Multiple R-squared:  0.2156, Adjusted R-squared:  0.2153 
#&gt; F-statistic: 650.1 on 1 and 2365 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-38-1.png" width="700" style="display: block; margin: auto;"></p>
<p>Finally, check these values against the comments in <code>make_indices.R</code> to be sure we’re calculating the same index:</p>
<pre><code>#&gt;          0%         25%         50%         75%        100% 
#&gt; -4.47333154 -0.57633937  0.06476722  0.93863134  3.52917748</code></pre>
</div>
</div>
<div id="fear-index" class="section level2">
<h2 class="hasAnchor">
<a href="#fear-index" class="anchor"></a>Fear index</h2>
<p>The following variables related to fear and violence :</p>
<ul>
<li>
<code>fear10</code>: Has avoided walking through dangerous areas</li>
<li>
<code>vic44</code>: Organized in Neighborhood for Security (0 = no, 1=yes)</li>
<li>
<code>vic1exta</code>: Victim of Crime (Frequency) (999999 if vic1ext=2, otherwise max=15)</li>
<li>
<code>vic1hogar</code>: Other Victim of Crime in Household (1=yes, 2=no)</li>
<li>
<code>aoj11</code>: Perception of Neighborhood Security (1 = safe, 4 = unsafe)</li>
<li>
<code>pese1</code>: Perception of Neighborhood Violence (1=high, 3=low)</li>
<li>
<code>pese2</code>: Trend in Neighborhood Violence (1=high, 3=low)</li>
<li>
<code>aoj17</code>: Gang Presence in Neighborhood (1 = a lot, 4 = none)</li>
<li>
<code>diso7</code>: Youth Loitering a Problem in the Neighborhood (1 = very serious, 5 = not a problem)</li>
<li>
<code>diso8</code>: Youth in Gangs a Problem in the Neighborhood (1 = very serious, 5 = not a problem)</li>
<li>
<code>diso10</code>: Illegal Drug Trafficking a Problem in the Neighborhood (1 = very serious, 5 = not a problem)</li>
<li>
<code>diso18</code>: Gang Fights a Problem in the Neighborhood (1 = very serious, 5 = not a problem)</li>
<li>
<code>diso14</code>: Drug Addicts a Problem in the Neighborhood (1 = very serious, 5 = not a problem)</li>
<li>
<code>diso16</code>: Assaults a Problem in the Neighborhood (1 = very serious, 5 = not a problem)</li>
<li>
<code>diso17</code>: Shootings a Problem in the Neighborhood (1 = very serious, 5 = not a problem)</li>
<li>
<code>vicbar1</code>: Burglaries in the Neighborhood (1=yes, 2=no)</li>
<li>
<code>vicbar1f</code>: Number of Occurrences of Burglaries in Neighborhood (1 = weekly, 3=yearly)</li>
<li>
<code>vicbar3</code>: Sales of Illegal Drugs in Neighborhood (1=yes, 2=no)</li>
<li>vicbar4: Extortion or Blackmail in the Neighborhood (1=yes, 2=no)</li>
<li>
<code>vicbar7</code>: Murders in the Neighborhood (1=yes, 2=no)</li>
<li>
<code>a4</code> == 5,14,27,30,57: Biggest problem related to crime/violence/security</li>
</ul>
<p><code>vic44</code> appears to be on-topic, but actually doesn’t correlate as strongly as the other variables do, so we’re leaving it out.</p>
<div id="principal-componnent-analysis-without-imputation-3" class="section level3">
<h3 class="hasAnchor">
<a href="#principal-componnent-analysis-without-imputation-3" class="anchor"></a>Principal Componnent Analysis without imputation</h3>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-40-1.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>#&gt; Importance of components:
#&gt;                           PC1    PC2     PC3     PC4     PC5     PC6     PC7
#&gt; Standard deviation     2.9789 2.2473 1.28048 1.13165 1.05098 0.94834 0.90026
#&gt; Proportion of Variance 0.3684 0.2097 0.06807 0.05316 0.04586 0.03734 0.03365
#&gt; Cumulative Proportion  0.3684 0.5781 0.64613 0.69929 0.74515 0.78248 0.81613
#&gt;                            PC8     PC9    PC10    PC11    PC12    PC13    PC14
#&gt; Standard deviation     0.89040 0.82758 0.76959 0.68699 0.65372 0.55793 0.51536
#&gt; Proportion of Variance 0.03291 0.02843 0.02459 0.01959 0.01774 0.01292 0.01103
#&gt; Cumulative Proportion  0.84904 0.87747 0.90206 0.92166 0.93940 0.95232 0.96335
#&gt;                          PC15    PC16    PC17    PC18    PC19
#&gt; Standard deviation     0.4909 0.44155 0.41784 0.39339 0.34304
#&gt; Proportion of Variance 0.0100 0.00809 0.00725 0.00642 0.00489
#&gt; Cumulative Proportion  0.9734 0.98144 0.98869 0.99511 1.00000
#&gt;                                         PC20                  PC21
#&gt; Standard deviation     0.0000000000000001235 0.0000000000000000405
#&gt; Proportion of Variance 0.0000000000000000000 0.0000000000000000000
#&gt; Cumulative Proportion  1.0000000000000000000 1.0000000000000000000</code></pre>
<p>41.3% of total variance winds up in the first component. ### Missing values imputation</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-41-1.png" width="700" style="display: block; margin: auto;"></p>
<p>The only variable that needed a lot of imputation was <code>vicbar1f</code> – the number of burglaries in the neighborhood. I’m guessing this is because people don’t always know about all the burglaries that might be going on. Let’s look at the PCA for one of our imputed datasets.</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-42-1.png" width="700" style="display: block; margin: auto;"></p>
<p>Imputation decreased the fraction of variance in the first component to 46.7%.</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-43-1.png" width="700" style="display: block; margin: auto;"></p>
</div>
<div id="scatterplot-matrix-3" class="section level3">
<h3 class="hasAnchor">
<a href="#scatterplot-matrix-3" class="anchor"></a>Scatterplot matrix</h3>
<p>The distribution along PC1 looks pretty continuous, while the PC2 distribution looks very skewed. Fortunately, we’re only using PC1.</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-44-1.png" width="700" style="display: block; margin: auto;"></p>
<p>Correlations are high, and the distribution is skewed toward high values.</p>
</div>
<div id="influence-of-indicator-3" class="section level3">
<h3 class="hasAnchor">
<a href="#influence-of-indicator-3" class="anchor"></a>Influence of indicator</h3>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-45-1.png" width="960" style="display: block; margin: auto;"></p>
<p>The <code>diso</code> variables all increase dramatically, while <code>aoj11</code> shows a dramatic decrease. This suggests that high values of the index indicate not being particularly concerned about crime and violence; we’ll have to reverse the scale.</p>
<p>Now, in each row of predict_data2, all values are those that will give a lower score, except for one.</p>
<p>Now you can see that all of the scores are reasonably close to the minimum value stored in minmax. <img src="Building_indices_files/figure-html/unnamed-chunk-49-1.png" width="700" style="display: block; margin: auto;"></p>
<p>All variables seem to have an effect, with a somewhat smaller one for <code>fear10</code> (avoided walking through dangerous areas), and larger ones for the <code>diso</code> variables and <code>vic1exta</code> (frequency of victimization)</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-50-1.png" width="700" style="display: block; margin: auto;"></p>
<p>Finally, check these values against the comments in <code>make_indices.R</code> to be sure we’re calculating the same index:</p>
<pre><code>#&gt;          0%         25%         50%         75%        100% 
#&gt; -2.70032557 -0.72584645  0.09710501  0.77728462  1.67932735</code></pre>
<p>Let’s see how people’s level of fear correlates with their answers to <code>a4</code> – the most serious problem facing the country. This is a little tricky, since the coding is consistent between countries (e.g. <code>a4=4</code> means poverty everywhere), but not all of the possible answers were on the questionnaire for any given country. If any country-specific answers turn out to be significant, we’ll have to make sure they’re significant at a country level as well.</p>
<pre><code>#&gt;    var val          pval         mean      othermean
#&gt; 1   a4   3 0.39488587575  0.029509748 -0.00610302484
#&gt; 2   a4   5 0.17732524348 -0.022524993  0.01760682407
#&gt; 3   a4   4 0.00286935992  0.166059636 -0.01152330313
#&gt; 4   a4   1 0.39223209524 -0.032747298  0.00433292296
#&gt; 5   a4  22 0.69044430807 -0.111120838 -0.00052025216
#&gt; 6   a4  18 0.00003948291  0.416773435 -0.00870279563
#&gt; 7   a4  55 0.89834944608  0.152383102 -0.00083033619
#&gt; 8   a4  59 0.56451288843 -0.117902722 -0.00029832609
#&gt; 9   a4  13 0.93441047454  0.004998676 -0.00095791131
#&gt; 10  a4  56 0.28889786594 -0.908938668  0.00003515715
#&gt; 11  a4  27 0.00903945811 -0.337846900  0.00388843830
#&gt; 12  a4  15 0.31782389988  0.183157003 -0.00198242310
#&gt; 13  a4  11 0.16200870293  0.256953430 -0.00150069332
#&gt; 14  a4   7 0.68575826222 -0.327494399 -0.00047589033
#&gt; 15  a4  19 0.06581848458  0.270684395 -0.00450883307
#&gt; 16  a4  24 0.76187965621  0.134907813 -0.00094200953
#&gt; 17  a4  57 0.27358566099 -0.094426065  0.00238241504
#&gt; 18  a4   9 0.39583031516  0.244713125 -0.00108683957
#&gt; 19  a4  70 0.62720770871 -0.085975376 -0.00010323370
#&gt; 20  a4  26 0.72087081306  0.166855714 -0.00087353287
#&gt; 21  a4   2 0.69617343314 -0.070997657 -0.00039104187
#&gt; 22  a4  58 0.27290900410 -0.300587828  0.00036012309
#&gt; 23  a4  21 0.39795926402 -0.150660812  0.00043107652
#&gt; 24  a4  30 0.14364439266  0.351689101 -0.00153853586
#&gt; 25  a4  61 0.77536856642  0.049207745 -0.00078501427
#&gt; 26  a4  32 0.85081039038 -0.123122986 -0.00065551802
#&gt; 27  a4  23 0.55528603244 -0.138956893 -0.00015360895
#&gt; 28  a4  10 0.73351121193 -0.152576953 -0.00049596192
#&gt; 29  a4  14 0.39871530236 -0.081301270  0.00128574720
#&gt; 30  a4  25 0.06013768892  0.733840247 -0.00173198416
#&gt; 31  a4  12 0.77125105735 -0.225738020 -0.00051583832</code></pre>
<p>So it looks like the only strong correlation here is that people who are concerned about human rights violations are significantly <em>less</em> fearful than the rest of the population.</p>
<p>Another unordered categorical variable would be <code>for1n</code> (Country with the most influence in the region).</p>
<pre><code>#&gt;      var val       pval        mean   othermean
#&gt; 1  for1n  10 0.37666515  0.06763577 -0.02470778
#&gt; 2  for1n   4 0.07170587 -0.04060593  0.02152791
#&gt; 3  for1n  12 0.54458109  0.06557680 -0.02374458
#&gt; 4  for1n   5 0.52933974  0.05241903 -0.02362855
#&gt; 5  for1n   2 0.42862872  0.01935427 -0.02659277
#&gt; 6  for1n   6 0.09925298  0.08384690 -0.02810900
#&gt; 7  for1n   1 0.24402069 -0.08654407 -0.01748146
#&gt; 8  for1n   7 0.39705639  0.08103923 -0.02441661
#&gt; 9  for1n  11 0.22250868  0.37767711 -0.02366665
#&gt; 10 for1n   3 0.37547399  0.12864467 -0.02411783</code></pre>
<pre><code>#&gt; [1] 0.7100317</code></pre>
<pre><code>#&gt; [1] 0.08713693</code></pre>
<p>So the 71% of people who feel that the USA (<code>for1n=4</code>) is the most influential country in the region are significantly more fearful than the remaining 29%, while the 9% who think Japan has the most influence (<code>for1n==2</code>) are less fearful than the remaining 91%. Everything else turns out not to be significant. I don’t really know what makes the people who perceive a high Japanese influence different from everyone else, but it’s a pretty big difference.</p>
</div>
</div>
<div id="transparency-index" class="section level2">
<h2 class="hasAnchor">
<a href="#transparency-index" class="anchor"></a>Transparency index</h2>
<ul>
<li>
<code>honqt1</code> : Transparency of the presidency of the republic (1 = very, 4 = not at all)</li>
<li>
<code>honqt2</code> : Transparency of the National Congress</li>
<li>
<code>honqt3</code> : Transparency of the Government Accountability Office</li>
<li>
<code>honqt4</code> : Transparency of the state enterprises (ENEE, SANAA, HONDUTEL etc.)</li>
<li>
<code>honqt5</code> : Transparency of the police</li>
<li>
<code>honqt6</code> : Transparency of the Armed Forces</li>
<li>
<code>honqt7</code> : Transparency of the Public Ministry</li>
<li>
<code>honqt8</code> : Transparency of the National Anticorruption Council</li>
<li>
<code>honqt9</code> : Transparency of the municipal government</li>
<li>
<code>honqt10</code> : Transparency of the Superior Court of Accounts</li>
<li>
<code>honqt11</code> : Transparency of the Institute for Access to Public Information</li>
<li>
<code>honqt12</code> : Transparency of the Supreme Electoral Tribunal</li>
</ul>
<div id="principal-componnent-analysis-without-imputation-4" class="section level3">
<h3 class="hasAnchor">
<a href="#principal-componnent-analysis-without-imputation-4" class="anchor"></a>Principal Componnent Analysis without imputation</h3>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-58-1.png" width="700" style="display: block; margin: auto;"></p>
<p>52% of total variance winds up in the first component.</p>
</div>
<div id="missing-values-imputation-3" class="section level3">
<h3 class="hasAnchor">
<a href="#missing-values-imputation-3" class="anchor"></a>Missing values imputation</h3>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-59-1.png" width="700" style="display: block; margin: auto;"></p>
<p>None of the variables have more than 20% missing; most everyone has an opinion about the police (<code>honqt5</code>) and fewer have one about the Institute for Access to Public Information (<code>honqt11</code>).</p>
<p>Now calculate PCA for each of the imputed datasets.</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-60-1.png" width="700" style="display: block; margin: auto;"></p>
<p>Imputation decreased the fraction of variance in the first component slightly to 52% – still pretty good.</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-61-1.png" width="700" style="display: block; margin: auto;"></p>
</div>
<div id="scatterplot-matrix-4" class="section level3">
<h3 class="hasAnchor">
<a href="#scatterplot-matrix-4" class="anchor"></a>Scatterplot matrix</h3>
<p>PC1 is a little bit “stripy”, but still shows a decent distribution.</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-62-1.png" width="700" style="display: block; margin: auto;"></p>
<p>Correlations between imputed datasets are high; distributions look good.</p>
</div>
<div id="influence-of-indicator-4" class="section level3">
<h3 class="hasAnchor">
<a href="#influence-of-indicator-4" class="anchor"></a>Influence of indicator</h3>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-63-1.png" width="960" style="display: block; margin: auto;"></p>
<p>All values increase (toward less transparency) as the index increases – need to flip sign below.</p>
<p>Now, in each row of predict_data2, all values are those that will give a lower score, except for one.</p>
<p>Now you can see that all of the scores are reasonably close to the minimum value stored in minmax. <img src="Building_indices_files/figure-html/unnamed-chunk-67-1.png" width="700" style="display: block; margin: auto;"></p>
<p>All variables have a nearly equal effect.</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-68-1.png" width="700" style="display: block; margin: auto;"></p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-69-1.png" width="700" style="display: block; margin: auto;"></p>
<p>Test significance of correlations between the index and the component variables using linear regression.</p>
<pre><code>#&gt;                                                                                                                                                                                                                                                         honqt1 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000012866746451298175113825478749774798 
#&gt;                                                                                                                                                                                                                                                         honqt2 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001493134 
#&gt;                                                                                                                                                                                                                                                         honqt3 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000021360978862046174 
#&gt;                                                                                                                                                                                                                                                         honqt4 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000529322922401291189127369670926592669644675500354991934630782761168339339154424228118644 
#&gt;                                                                                                                                                                                                                                                         honqt5 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000035626591481178471332736954147 
#&gt;                                                                                                                                                                                                                                                         honqt6 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000183875744383942303424458578543081031278342385868618849696 
#&gt;                                                                                                                                                                                                                                                         honqt7 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000975022148178720827893 
#&gt;                                                                                                                                                                                                                                                         honqt8 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003217731422688184753918230182307335921035165491332090986041892815994816 
#&gt;                                                                                                                                                                                                                                                         honqt9 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001008413214330762943578999779862835165894899204617601 
#&gt;                                                                                                                                                                                                                                                        honqt10 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000391362491585336679586853883 
#&gt;                                                                                                                                                                                                                                                        honqt11 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000098856364461899564714639031932120312358609586997038299117357239751650 
#&gt;                                                                                                                                                                                                                                                        honqt12 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016887682533802863839429010022571899095154</code></pre>
<p>All are highly significant.</p>
</div>
</div>
<div id="trust-in-government-index" class="section level2">
<h2 class="hasAnchor">
<a href="#trust-in-government-index" class="anchor"></a>Trust in Government Index</h2>
<p>The following is a proposal for a Trust in Government Index, for which the following variables were considered to be the most relevant in determining the citizens’ trust in all civic, public, political and governmental structures. The following variables were measured in all three countries.</p>
<ul>
<li>
<code>b1</code>: Courts Guarantee a Fair Trial (1=Not at all, 7=A lot)</li>
<li>
<code>b2</code>: Respect for Political Institutions (1=Not at all, 7=A lot)</li>
<li>
<code>b3</code>: Respect for Basic Rights (1=Not at all, 7=A lot)</li>
<li>
<code>b4</code>: Pride in Political System (1=Not at all, 7=A lot)</li>
<li>
<code>b6</code>: People Should Support the Political System (1=Not at all, 7=A lot)</li>
<li>
<code>b10a</code>: Trust in Judicial System (1=Not at all, 7=A lot)</li>
<li>
<code>b12</code>: Trust in Armed Forces (1=Not at all, 7=A lot)</li>
<li>
<code>b13</code>: Trust in National Legislature (1=Not at all, 7=A lot)</li>
<li>
<code>b18</code>: Trust in National Police (1=Not at all, 7=A lot)</li>
<li>
<code>b21</code>: Trust in Political Parties (1=Not at all, 7=A lot)</li>
<li>
<code>b21a</code>: Trust in Executive (1=Not at all, 7=A lot)</li>
<li>
<code>b32</code>: Trust in Local Government (1=Not at all, 7=A lot)</li>
<li>
<code>b47a</code>: Trust in Elections (1=Not at all, 7=A lot)</li>
<li>
<code>n9</code>: Evaluation of Administration’s Handling of Corruption (1=Not at all, 7=A lot)</li>
<li>
<code>n11</code>: Evaluation of Administration’s Handling of Citizen Security (1=Not at all, 7=A lot)</li>
<li>
<code>n15</code>: Evaluation of Administration’s Handling of Economy (1=Not at all, 7=A lot)</li>
<li>
<code>b3milx</code>: Armed Forces Respect Human Rights (1=Not at all, 7=A lot)</li>
</ul>
<div id="principal-componnent-analysis-without-imputation-5" class="section level3">
<h3 class="hasAnchor">
<a href="#principal-componnent-analysis-without-imputation-5" class="anchor"></a>Principal Componnent Analysis without imputation</h3>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-72-1.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>#&gt; Importance of components:
#&gt;                           PC1     PC2     PC3     PC4     PC5     PC6     PC7
#&gt; Standard deviation     4.7039 2.03156 1.81745 1.69101 1.69012 1.51693 1.48483
#&gt; Proportion of Variance 0.4009 0.07478 0.05985 0.05181 0.05176 0.04169 0.03995
#&gt; Cumulative Proportion  0.4009 0.47570 0.53555 0.58736 0.63912 0.68081 0.72076
#&gt;                            PC8     PC9    PC10    PC11    PC12    PC13    PC14
#&gt; Standard deviation     1.41754 1.35088 1.32148 1.28392 1.27975 1.22002 1.18838
#&gt; Proportion of Variance 0.03641 0.03307 0.03164 0.02987 0.02967 0.02697 0.02559
#&gt; Cumulative Proportion  0.75717 0.79023 0.82188 0.85174 0.88142 0.90839 0.93398
#&gt;                           PC15    PC16    PC17
#&gt; Standard deviation     1.16032 1.15142 0.98574
#&gt; Proportion of Variance 0.02439 0.02402 0.01761
#&gt; Cumulative Proportion  0.95837 0.98239 1.00000</code></pre>
<p>Without imputation, 40% of variance is concentrated in the first principal component.</p>
</div>
<div id="missing-values-imputation-4" class="section level3">
<h3 class="hasAnchor">
<a href="#missing-values-imputation-4" class="anchor"></a>Missing values imputation</h3>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-73-1.png" width="700" style="display: block; margin: auto;"></p>
<p>None of the variables stand out as needing really dramatic levels of imputation.</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-74-1.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>#&gt; Importance of components:
#&gt;                           PC1     PC2     PC3     PC4     PC5     PC6     PC7
#&gt; Standard deviation     4.7346 2.05134 1.83378 1.72003 1.68853 1.53611 1.49190
#&gt; Proportion of Variance 0.3987 0.07485 0.05981 0.05262 0.05071 0.04197 0.03959
#&gt; Cumulative Proportion  0.3987 0.47359 0.53340 0.58602 0.63674 0.67871 0.71830
#&gt;                            PC8    PC9    PC10    PC11   PC12   PC13    PC14
#&gt; Standard deviation     1.44328 1.3662 1.32795 1.31246 1.2855 1.2344 1.21382
#&gt; Proportion of Variance 0.03705 0.0332 0.03137 0.03064 0.0294 0.0271 0.02621
#&gt; Cumulative Proportion  0.75535 0.7885 0.81992 0.85056 0.8800 0.9071 0.93326
#&gt;                           PC15    PC16   PC17
#&gt; Standard deviation     1.17502 1.17062 1.0004
#&gt; Proportion of Variance 0.02456 0.02438 0.0178
#&gt; Cumulative Proportion  0.95782 0.98220 1.0000</code></pre>
<p>Following imputation, 39.8% of variance remained concentrated in the first principal component.</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-75-1.png" width="700" style="display: block; margin: auto;"></p>
</div>
<div id="scatterplot-matrix-5" class="section level3">
<h3 class="hasAnchor">
<a href="#scatterplot-matrix-5" class="anchor"></a>Scatterplot matrix</h3>
<p>The distribution along PC1 seems smooth, indicating that this isn’t dominated by a single variable.</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-76-1.png" width="700" style="display: block; margin: auto;"></p>
<p>Correlations between imputations are high; distributions are well-behaved.</p>
</div>
<div id="influence-of-indicator-5" class="section level3">
<h3 class="hasAnchor">
<a href="#influence-of-indicator-5" class="anchor"></a>Influence of indicator</h3>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-77-1.png" width="960" style="display: block; margin: auto;"></p>
<p>All variables tend to increase with PC1; recall that higher values indicate more trust in government institutions. Our index is pointing in the right direction.</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-78-1.png" width="700" style="display: block; margin: auto;"></p>
<p>All variables seem to have a significant impact on the score. Because all variables take on multiple values, we can obtain p-values froml linear regression.</p>
<pre><code>#&gt;                                                                                                                                                                                                                                                                                                                       b1 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000621855 
#&gt;                                                                                                                                                                                                                                                                                                                       b2 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044702458928341243742076307414460222654509453674273927276967549892595 
#&gt;                                                                                                                                                                                                                                                                                                                       b3 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                                                                                                                                                                                                       b4 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                                                                                                                                                                                                       b6 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                                                                                                                                                                                                     b10a 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                                                                                                                                                                                                      b12 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001941337286337637234319111 
#&gt;                                                                                                                                                                                                                                                                                                                      b13 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                                                                                                                                                                                                      b18 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                                                                                                                                                                                                      b21 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                                                                                                                                                                                                     b21a 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                                                                                                                                                                                                      b32 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                                                                                                                                                                                                     b47a 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                                                                                                                                                                                                       n9 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                                                                                                                                                                                                      n11 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                                                                                                                                                                                                      n15 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                                                                                                                                                                                                   b3milx 
#&gt; 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000</code></pre>
<p>All are highly significant.</p>
<pre><code>#&gt; 
#&gt; Call:
#&gt; lm(formula = q ~ w, data = b2)
#&gt; 
#&gt; Residuals:
#&gt;     Min      1Q  Median      3Q     Max 
#&gt; -5.6715 -1.0620  0.0324  1.1189  4.1601 
#&gt; 
#&gt; Coefficients:
#&gt;             Estimate Std. Error t value            Pr(&gt;|t|)    
#&gt; (Intercept)  4.77866    0.02388  200.10 &lt;0.0000000000000002 ***
#&gt; w           -0.84894    0.02394  -35.46 &lt;0.0000000000000002 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; Residual standard error: 1.6 on 4487 degrees of freedom
#&gt; Multiple R-squared:  0.2189, Adjusted R-squared:  0.2188 
#&gt; F-statistic:  1258 on 1 and 4487 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-80-1.png" width="700" style="display: block; margin: auto;"></p>
<p>Finally, check these values against the comments in <code>make_indices.R</code> to be sure we’re calculating the same index:</p>
<pre><code>#&gt;            0%           25%           50%           75%          100% 
#&gt; -2.6610564580 -0.7163719385  0.0002760177  0.7000412597  2.5107731561</code></pre>
</div>
</div>
<div id="wealth-index" class="section level2">
<h2 class="hasAnchor">
<a href="#wealth-index" class="anchor"></a>Wealth index</h2>
<p>A composite wealth index from Americas Barometer indicators can be built from the following:</p>
<ul>
<li>
<code>r3</code>: Refrigerator in home (0 = No, 1 = Yes)</li>
<li>
<code>r4</code>: Landline in home</li>
<li>
<code>r4a</code>: Cell phone in home</li>
<li>
<code>r5</code>: Number of vehicles owned (0 = None, 1 = one, 2 = two, 3 = three or more)</li>
<li>
<code>r6</code>: Washing machine in home</li>
<li>
<code>r7</code>: Microwave oven in home</li>
<li>
<code>r8</code>: Owns motorcycle</li>
<li>
<code>r12</code>: Drinking water in home</li>
<li>
<code>r14</code>: Indoor bathroom in home</li>
<li>
<code>r15</code>: Computer in home</li>
<li>
<code>r18</code>: Internet access in home</li>
<li>
<code>r1</code>: Television in home</li>
<li>
<code>r16</code>: Flat-panel TV in home</li>
<li>
<code>r26</code>: Home connected to sewage system</li>
<li>
<code>q10new</code>: Monthly household income (scale of 0-16)</li>
<li>
<code>q10g</code>: Monthly personal income (scale of 0-16)</li>
</ul>
<div id="principal-componnent-analysis-without-imputation-6" class="section level3">
<h3 class="hasAnchor">
<a href="#principal-componnent-analysis-without-imputation-6" class="anchor"></a>Principal Componnent Analysis without imputation</h3>
<pre><code>#&gt; [1] 1856</code></pre>
<p>If we just ignore any rows with missing values, we’ll end up with only 647 rows left – 41% of what we started with. How many values are we missing, anyway?</p>
<pre><code>#&gt; [1] 0.04829111</code></pre>
<p>So we’re only missing about 4% of values – it hurts my heart to throw away 59% of the data because of that. It also might introduce biases (for example if poor or rich people are more likely to not answer questions). For now, though, I’ll endure the pain and see what PCA looks like with just the complete data:</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-84-1.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>#&gt; Importance of components:
#&gt;                           PC1    PC2     PC3     PC4     PC5     PC6     PC7
#&gt; Standard deviation     5.8088 2.0978 0.73076 0.53007 0.45229 0.42231 0.40846
#&gt; Proportion of Variance 0.8363 0.1091 0.01323 0.00696 0.00507 0.00442 0.00413
#&gt; Cumulative Proportion  0.8363 0.9453 0.95856 0.96553 0.97060 0.97502 0.97915
#&gt;                            PC8     PC9   PC10    PC11    PC12    PC13    PC14
#&gt; Standard deviation     0.38344 0.36871 0.3534 0.34253 0.32093 0.29195 0.27112
#&gt; Proportion of Variance 0.00364 0.00337 0.0031 0.00291 0.00255 0.00211 0.00182
#&gt; Cumulative Proportion  0.98280 0.98616 0.9893 0.99217 0.99472 0.99683 0.99866
#&gt;                           PC15                   PC16
#&gt; Standard deviation     0.23294 0.00000000000000006369
#&gt; Proportion of Variance 0.00134 0.00000000000000000000
#&gt; Cumulative Proportion  1.00000 1.00000000000000000000</code></pre>
<p>83% of the variance is in the first component, which is pretty good. Note that people typically recommend using <code>scale=TRUE</code>; the reason I didn’t is because one of our variables (<code>r1</code>, TV in home) has a variance of zero in this dataset – everyone counted said “yes”. This gives us a divide-by-zero error when we scale, which is no good.</p>
<p>We can look at a scatterplot of the first two principal components:</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-85-1.png" width="700" style="display: block; margin: auto;"></p>
<p>These are the two principal components along which the variation is the most spread-out. The lattice-like pattern comes from the fact that we’re seeing a projection of variables that can only take on certain discrete values, as opposed to continuous ones. In the ideal case, most of the variance would be in the first component, but this isn’t too bad. If you want to see how some of the other dimenisions look, try changing the values 1 and 2 to others, up to 17 (which should contain the least variance).</p>
<p>Now let’s try imputing those missing values.</p>
<p>There are a few different multiple imputation schemes available in R, but it’s hard to find a good explanation of them. <a href="http://pj.freefaculty.org/guides/Rcourse/multipleImputation/multipleImputation-1-lecture.pdf">This one</a> is OK, for being a really long powerpoint. I’ll try doing this using the <code>mice</code> package (Multivariate Imputation by Chained Equations) and see how it does. More about MICE <a href="http://www.stefvanbuuren.nl/mi/MICE.html">here</a>.</p>
</div>
<div id="missing-values-imputation-5" class="section level3">
<h3 class="hasAnchor">
<a href="#missing-values-imputation-5" class="anchor"></a>Missing values imputation</h3>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-86-1.png" width="700" style="display: block; margin: auto;"></p>
<p>There’s a lot going on in the output here. MICE generated 5 different imputed data sets, so that we can run the same analyses on each and see how they compare. Some columns have a lot more missing cells than others – everybody knows whether they have a washing machine (<code>r6</code>), but flat-panel TVs (<code>r16</code>) caused some confusion, and a lot of people didn’t disclose their personal income (<code>q10g</code>). The PredictorMatrix at the bottom shows which variables were used to predict others. Except for <code>r6</code> and <code>r15</code>, which didn’t need predicting at all, it looks like everything was used to predict everything else.</p>
<pre><code>#&gt; &lt; table of extent 0 &gt;</code></pre>
<p>Fortunately, non-responses to <code>q10g</code> came from the three countries in roughly equal fractions.</p>
<p>Here’s an example from one row that had some missing values (<code>r1</code>, <code>r16</code>, and <code>q10g</code>):</p>
<pre><code>#&gt;   q10g q10new r1 r12 r14 r15 r16 r18 r26 r3 r4 r4a r5 r6 r7 r8
#&gt; 1   NA      3  0   0   0   0  NA   0   0  0  0   0  0  0  0  0</code></pre>
<pre><code>#&gt;      q10g q10new r1 r12 r14 r15 r16 r18 r26 r3 r4 r4a r5 r6 r7 r8
#&gt; [1,] 2    3      0  0   0   0   0   0   0   0  0  0   0  0  0  0 
#&gt; [2,] 2    3      0  0   0   0   1   0   0   0  0  0   0  0  0  0 
#&gt; [3,] 2    3      0  0   0   0   1   0   0   0  0  0   0  0  0  0 
#&gt; [4,] 1    3      0  0   0   0   0   0   0   0  0  0   0  0  0  0 
#&gt; [5,] 1    3      0  0   0   0   0   0   0   0  0  0   0  0  0  0</code></pre>
<p>This family doesn’t have much stuff and their income is low, but 3 of the 5 predictions gave them a flat-panel TV. These might not be reliable predictions. The personal income (<code>q10g</code>) varies between imputed datasets, but tends to be at the low end and is probably more trustworthy.</p>
<p>Now let’s do the PCA calculation. We’ll generate a structure called <code>pr</code> that contains the results of 5 different PCA calculations for the 5 imputed datasets.</p>
<p>We can visualize the fraction of variance contained in each of the 17 principal components to see to what extent variance is concentrated in the first few. (Do this for just the first imputed model.)</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-90-1.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>#&gt; Importance of components:
#&gt;                           PC1     PC2     PC3     PC4     PC5     PC6     PC7
#&gt; Standard deviation     5.8632 1.98226 0.73868 0.52587 0.42772 0.40966 0.40726
#&gt; Proportion of Variance 0.8476 0.09689 0.01345 0.00682 0.00451 0.00414 0.00409
#&gt; Cumulative Proportion  0.8476 0.94452 0.95798 0.96480 0.96931 0.97345 0.97754
#&gt;                            PC8     PC9    PC10    PC11    PC12    PC13    PC14
#&gt; Standard deviation     0.36683 0.36088 0.34365 0.32799 0.32573 0.32116 0.29709
#&gt; Proportion of Variance 0.00332 0.00321 0.00291 0.00265 0.00262 0.00254 0.00218
#&gt; Cumulative Proportion  0.98085 0.98406 0.98698 0.98963 0.99225 0.99479 0.99696
#&gt;                           PC15    PC16
#&gt; Standard deviation     0.27551 0.21724
#&gt; Proportion of Variance 0.00187 0.00116
#&gt; Cumulative Proportion  0.99884 1.00000</code></pre>
<p>About 85% of the total variance is concentrated in the first component, roughly the same as before imputation – this means our imputation didn’t mess things up too much (not yet, at least). What if we make a scatter plot of the first two components (for just one of the imputed datasets)?</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-91-1.png" width="700" style="display: block; margin: auto;"></p>
</div>
<div id="scatterplot-matrix-6" class="section level3">
<h3 class="hasAnchor">
<a href="#scatterplot-matrix-6" class="anchor"></a>Scatterplot matrix</h3>
<p>We want to be sure that all five of our imputed datasets are measuring the same thing. We can do this by plotting all of the pairwise scatterplots; R makes this easy for us, if we put them all in one data frame first.</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-92-1.png" width="960" style="display: block; margin: auto;"></p>
<p>What is this showing? <code>imp1</code> through <code>imp5</code> are our five imputed datasets, and we’re looking at the first principal component from each. On the diagonal of this matrix, we see distribution plots for each of them – they all look really similar. Above the diagonal, we get pairwise correlations; for example <code>imp1</code> and <code>imp2</code> have a correlation of 0.912. All of these are fairly high. Below the diagonal, we see scatter plots for each pair of imputations. There are some disagreements, but in general they match up quite well. Averaging all five should help smooth out some of those cases where they disagree.</p>
</div>
<div id="influence-of-indicator-6" class="section level3">
<h3 class="hasAnchor">
<a href="#influence-of-indicator-6" class="anchor"></a>Influence of indicator</h3>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-93-1.png" width="960" style="display: block; margin: auto;"></p>
<p>The <code>q10</code> variables increase dramatically from the lowest to the highest quartile, which makes sense as these are direct measures of income. The other variables all show more modest increases – rich people own more things, but a household’s assets are a function of more than just their income.</p>
<p>We can see more details about how the top and bottom quantiles differ. For example, nearly everyone in the top 25% has a refrigerator (<code>r3</code>), a cell phone (<code>r4a</code>), indoor drinking water (<code>r12</code>), and a television (<code>r1</code>), but motorcycles (<code>r8</code>) are pretty rare. In the bottom 25%, more people have cell phones (<code>r4a</code>) than indoor bathrooms (<code>r14</code>).</p>
<p>As another sanity check, let’s look at the distribution of values from our composite index. First, we’ll figure out what the hypothetical maximum and minimum values of the wealth index are, then we’ll plot those together with the actual density distribution.</p>
<p>We’ll adjust the score to have a mean of 0 and standard deviation of 1. The new value will be in a column called <code>norm</code>.</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-94-1.png" width="700" style="display: block; margin: auto;"></p>
<p>Our data uses the full range of possible wealth values, and tends to be somewhat bunched up at the low end.</p>
<p>To understand our index better, we can ask how different types of responses contribute to it. In other words, how much does it add to someone’s wealth index if they have a TV, or a motorcycle, or if their income increases by one level on the 16-point scale?</p>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-95-1.png" width="700" style="display: block; margin: auto;"><img src="Building_indices_files/figure-html/unnamed-chunk-96-1.png" width="672" style="display: block; margin: auto;"></p>
<p>Clearly, the indicators that measure income directly have a much larger influence on our wealth index than the others. Each 1-point increase in household income (<code>q10new</code>) increases the wealth index by 0.13, while the increases based on possessions average to about 0.004. Having a microwave oven (<code>r7</code>) increases a person’s wealth index more than having a cell phone (<code>r4a</code>). Even poor people have cell phones, while microwaves tend to show a large difference between rich and poor households.</p>
<p>How do we know whether this is really a good composite index? We’ve seen a few good signs already – it captures most of the variance in the underlying indicators, it’s robust to random variations in multiple imputation, and it’s fairly nicely-distributed. The other thing to look for is how well it does at predicting the values of the individual variables – a good wealth index should do a reasonable job of predicting how much income someone has and which things they own.</p>
<p>First, let’s look at income (<code>q10new</code>):</p>
<pre><code>#&gt; 
#&gt; Call:
#&gt; lm(formula = q ~ w, data = q10new)
#&gt; 
#&gt; Residuals:
#&gt;     Min      1Q  Median      3Q     Max 
#&gt; -5.9449 -0.5611 -0.1626  0.3747  6.4719 
#&gt; 
#&gt; Coefficients:
#&gt;             Estimate Std. Error t value            Pr(&gt;|t|)    
#&gt; (Intercept)  7.13151    0.01621   440.0 &lt;0.0000000000000002 ***
#&gt; w            4.38437    0.01586   276.5 &lt;0.0000000000000002 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; Residual standard error: 1.042 on 4128 degrees of freedom
#&gt; Multiple R-squared:  0.9488, Adjusted R-squared:  0.9487 
#&gt; F-statistic: 7.644e+04 on 1 and 4128 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-97-1.png" width="700" style="display: block; margin: auto;"></p>
<p>Now, what about microwave ownership (<code>r7</code>)?</p>
<pre><code>#&gt; 
#&gt; Call:
#&gt; glm(formula = r ~ w, family = binomial(logit), data = r7)
#&gt; 
#&gt; Deviance Residuals: 
#&gt;     Min       1Q   Median       3Q      Max  
#&gt; -1.5683  -0.7855  -0.5388   0.9586   2.2643  
#&gt; 
#&gt; Coefficients:
#&gt;             Estimate Std. Error z value            Pr(&gt;|z|)    
#&gt; (Intercept) -1.13484    0.03763  -30.16 &lt;0.0000000000000002 ***
#&gt; w            0.84659    0.03721   22.75 &lt;0.0000000000000002 ***
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; (Dispersion parameter for binomial family taken to be 1)
#&gt; 
#&gt;     Null deviance: 5350.2  on 4574  degrees of freedom
#&gt; Residual deviance: 4757.1  on 4573  degrees of freedom
#&gt; AIC: 4761.1
#&gt; 
#&gt; Number of Fisher Scoring iterations: 4</code></pre>
<p><img src="Building_indices_files/figure-html/unnamed-chunk-98-1.png" width="700" style="display: block; margin: auto;"></p>
<p>This fit isn’t quite as pretty as <code>q10new</code> was, but the summary from the logistic regression calculation tells us that our wealth index has a highly-significant impact on microwave oven ownership. We can also see on the plot that the non-owners (<code>r7</code> = 0) are bunched up at the low-wealth end of the spectrum, as we’d expect. It should be easy to modify these plots for some of the other variables; you can see which ones are well-predicted by our wealth index and which ones might not be as much.</p>
<p>We can test this more rigorously using 2-sample t-tests:</p>
<pre><code>#&gt;                                                                                                                                                                                                 r3 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004939901648442254 
#&gt;                                                                                                                                                                                                 r4 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000388411359300111378748615758610724123522241398979609332964839360959137375539313682280412244361745 
#&gt;                                                                                                                                                                                                r4a 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000009931084417814842971965050708761192936929203698881974509280901322754222547044839068308863133721044806633154323388556108 
#&gt;                                                                                                                                                                                                 r6 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002025310746242367653360146370615299813417470451340321144090052498757339502804 
#&gt;                                                                                                                                                                                                 r7 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000035950892047094778331436146935291919443949831945992724738038480733012874588 
#&gt;                                                                                                                                                                                                 r8 
#&gt; 0.000000000000683400306298937114935874232716724152700456251796623519112472422420978546142578125000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
#&gt;                                                                                                                                                                                                r12 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000270983795569041359136713301270592248929014242766469271576320504957509627240997259954649839338758383368256003833 
#&gt;                                                                                                                                                                                                r14 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000210120594095515 
#&gt;                                                                                                                                                                                                r15 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007917815 
#&gt;                                                                                                                                                                                                r18 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000169618901974041453017 
#&gt;                                                                                                                                                                                                 r1 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000108964534242492160859578261426 
#&gt;                                                                                                                                                                                                r16 
#&gt; 0.000000000000000000000000000000000000000000000000000000000248729883184247826969984626022397251030002520567355037261816667564120551401471774039278608613064202574272043378048933515954286377699588 
#&gt;                                                                                                                                                                                                r26 
#&gt; 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011765352776201725919405289110725679474572131936462997897318</code></pre>
<p>All of our p-values on logistic regressions are highly significant, meaning that our wealth index has a strong influence on all of these wealth-related variables. This is what we would expect! Notice that the smallest p-values (i.e. the highest significance) are for variables like <code>r14</code> and <code>r18</code> where the influence on the wealth index was higher. This is also what we would expect; variables like <code>r8</code> are still significant but not as strong.</p>
<p>Finally, check these values against the comments in <code>make_indices.R</code> to be sure we’re calculating the same index:</p>
<pre><code>#&gt;         0%        25%        50%        75%       100% 
#&gt; -1.6224926 -0.8582592 -0.1299970  0.7725188  2.3979902</code></pre>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Edouard Legoupil, Hisham Galal.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
